In [4]:
%%timeit
import numpy as np

N = 10 ** 7

x = np.random.random(N)
s2 = x.sum()

78.2 ms ± 332 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [5]:
%%timeit
s1 = 0
for i in range(N):
    s1 += x[i]

1.31 s ± 46.7 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


# Медиана
https://numpy.org/doc/stable/reference/generated/numpy.median.html#numpy.median


In [11]:
a = np.array([[10, 7, 4], [3, 2, 1]], np.int32)
a

array([[10,  7,  4],
       [ 3,  2,  1]])

In [7]:
np.median(a, axis=0)

array([6.5, 4.5, 2.5])

In [8]:
np.median(a, axis=1)

array([7., 2.])

In [9]:
np.median(a)

3.5

In [10]:
np.average(a, axis=1)

array([7., 2.])

# The N-dimensional array (ndarray)

In [12]:
x = np.array([[1, 2, 3], [4, 5, 6]], np.int32)
type(x)

numpy.ndarray

In [13]:
x.shape

(2, 3)

In [14]:
x.dtype

dtype('int32')

In [15]:
# The element of x in the *second* row, *third* column, namely, 6.
x[1, 2]

6

In [17]:
y = x[:,1]
y

array([2, 5])

In [18]:
y[0] = 9 # !!! this also changes the corresponding element in x
y

array([9, 5])

In [19]:
x

array([[1, 9, 3],
       [4, 5, 6]])

# ин-плейс (in-place) модификация

In [23]:
numbers = [1, 2, 3, 4, 5]
slice = numbers[2:4]

print(numbers)  # [1, 2, 3, 4, 5]
print(slice)    # [3, 4]

[1, 2, 3, 4, 5]
[3, 4]


In [24]:
slice[0] = 100

print(numbers)  # [1, 2, 3, 4, 5]
print(slice)    # [100, 4]

[1, 2, 3, 4, 5]
[100, 4]


In [25]:
numbers = [1, 2, 3, 4, 5]
numbers[2:4] = [100, 200]

print(numbers)  # [1, 2, 100, 200, 5]  in-place

[1, 2, 100, 200, 5]


------------------------------------------------------

In [27]:
import math

def mean1D(x):
    s = 0
    for number in x:
        s += number
    return s / x.size


def std1D(x, mean):
    s = 0
    for number in x:
        s += (number - mean) ** 2
    return math.sqrt(s / x.size)

In [29]:
import numpy as np

N = 100 # размер массива
x = np.random.random(N)

mean_1 = mean1D(x)
mean_2 = x.mean()
std_1 = std1D(x, mean_1)
std_2 = x.std()


print(mean_1, mean_2)
print(std_1, std_2)

0.501271806912897 0.5012718069128972
0.2684693785134011 0.26846937851340114


In [31]:
# Векторизованные версии

def mean1D_vectorized(x):
    return x.sum() / x.size

def std1D_vectorized(x, mean):
    return np.sqrt(((x - mean) ** 2).sum() / x.size)

print(x.std(), std1D_vectorized(x, x.mean()))
print(x.mean(), mean1D_vectorized(x))

0.26846937851340114 0.26846937851340114
0.5012718069128972 0.5012718069128972
